#!/bin/bash

##############################
########## ENGLISH ###########
##############################

## strips `#####`
ST="###########"
BST="############################################"
#HELP
h="Usage: ./install.sh [OPTION] -l={ita | eng}\n\n  -c, --check\t\t\tMake checks during compiling.\n  -s, --stripping\t\tEnable erasing of debug simbols after compiling.\n  -o, --optimize\t\t\tEnable optmization flag for fast compiling ***WARNING***\n  -m, --no-sum\t\t\tNo MD5 control (don't use this if you are not sure!).\n  -l=<TYPE>, --language=<TYPE>\tRun script in different languages (eng, ita, fra).\n  -h, --help\t\t\tPrint this help.\n  -V, --version\t\t\tPrint version number.\n\nBy default the script is run in englisgh language, don't execute\nany kind of control in compiling and don't erase debug simbols.\nAll options results disabled.\n\n"
### version
version="QLFS install.sh version: $VERSION \nWritten by Marco Sciatta and Matteo Mattei.\n\nCopyleft (C) QLFS ;P\nhttp://qlfs.spaghettilinux.org\n\nThis program is distribuited under GPL. So it's possible to\nchange and share it witohout any problems.\nFor more details read the GPL licence attached into the script.\n"
## opz not recognized
opz="Unknow Option";
### message checking kernel and gcc
msck1="I found a kernel "
msck2="compiled with gcc "
mserr1="A kernel "
mserr2="it's necessary to compile qlfs-6.1\nImpossible to continue on the execution of the script."
msok1="The kernel "
msok2="respect the requirements, but it's compiled with an old version of gcc "
msok3="not recent and is not possible to continue on the execution of the script."
# Format
MET="########################################\n# EXT2 FILE SYSTEM SELECTED #\n########################################"
MRT="############################################\n# REISERFS FILE SYSTEM SELECTED #\n############################################"
MET3="########################################\n# EXT3 FILE SYSTEM SELECTED #\n########################################"
M1T="format in progress..."
M2T="format complete"
MFT="An error has occurred during the format process on "
#install.sh
### 4 multipartition
una="How many partitions u want to create [1-4]??"
instT2bis="Please insert the partitiion in which mount"
pch="Partition to create "
instT3bis="The selected partition for :"
####
instT1="You must be root for run this script."
instTM="Welcome to the fantastic world of Linux From Scratch!!!\nThis script will automate all the work that you will have to carry out.\nThis script is issued under the GPL license and than, can be used\nmodified and redistribuited without no problems ;-)\n"
instTT="This is the partition table of your machine"
instT2="Please insert the partition in which mount LFS: [/dev/hdaX]"
instSWAP="Do you have a partition for swap?"
instSWAP1="Please enter the partition for swap: [/dev/hdaY]"
instSWAP2="Swap partition is now ready..."
instSWAP3="Bad partition... takes shared swap"
instT3="The selected patition for / is: "
instT4="Are you sure to continue?"
instT5="The partition you typed do not exists!"
instTFP1="Are you surest to format the partition "
instTFP2="Check before that the selected partition is the corrected one.\nYou will lose ALL of your data on this partition! Continue?"
FSsT="Choose the File System type [DEFAULT == EXT3]\nType :\n1 ==> EXT3\n2 ==> EXT2\n3 ==> REISERFS\n"
FSqT="Type a number (1-3)"
instTMT="Mount the partition "
instTMK="Correctly mounted!"
instTMF="Mount Impossible on "
instTPA="Prepare the ambient for the compilation"     
instTPU="Please insert the password for the lfs user: "
instTAPU="Set permission for the lfs user"
instTF="Now launch the login script by typing '/tmp/lfs/bashlogin.sh'"
#bashlogin.sh
mT1="For starting the creation of the temporary system launch the command: '/tmp/lfs/step1.sh'."
#Step1.sh
SDT1="You alredy have all the source of lfs "
SDTP="Please insert the path of the directory in wich packages are: "
SDTF="The directory is not valid: "
SDTS="The directory typed is:"
SCTP="Copy all the file in progress..."
SCTW="The script will supply at the automatic download\nof all the source from the server: "
SCTC="Download of the source complete..."
SDCTK="Control checksum on all the packages in progress..."
SDCTKK="checksum correctly executed..."
SDCTKP="Some problems with the checksum of the source..."
SDCTSC="CREATION OF THE TEMPORARY SYSTEM\nStarting compilation"
STTF="FINE STEP 1\nWrite 'exit' and so 'logout' to return at the root user.\nThen run '/tmp/lfs/step2.sh'."
MSTR="# Stripping"
#Step2.sh
STTDF="For go on the installation, launch the step3 by typing 'sh step3.sh'."
MNTPD="#  Mounting the proc and devpts file systems"
ECH="# Entering the chroot environment"
#Step3.sh
STTPF="Now launch step 4: 'sh step4.sh'."
CHO="# Changing ownership"
MKD="# Creating directories"
CSY="# Creating essential symlinks"
PGLF="# Creating the passwd, group and log files"
#Step4.sh
STTWDC="Waiting for the check of the directory with the source"
STTFF="Now proceed with the compilation by launching step5 so: 'sh step5.sh'."
MKDE="# Creating /dev directory         #"
#Step5.sh
EOC="YOU HAVE FINISHED THE 6th CHAPTER ..."
CCF="# Console Configuration     "
ICF="# inputrc Configuration      "
BCF="# Bash Configuration      "
NCF="# Script Localnet "
STTCR="# Network Configuration "
STTCF="LFS SYSTEM INSTALLED!!!\nNow write exit until you not return at the root user of the host system\nafter returns at the root of the host system, launch the step6 for\ninitializing your systen with '/tmp/lfs/step6.sh'"
#step6.sh
STTNRS="### REMOVING SCRIPT FILES ###"
STTWP="Please waiting..."
STTBLS="The script will try to create a new entry on your bootloader.\nPlease tell me which bootloader is present on your pc\n'G' for Grub\n'L' for Lilo\n'N' for Other\n"
STTDP="Please insert the partition on which is installed LFS "
STTAR="The system needs to be rebooted, type ENTER to automatically reboot,\notherwise write 'no' and manually reboot later."
SRAT="automatically reboot"
SRMT="manually reboot"
STTBC="It's necessary to upadate your bootloader before you can start LFS!"
KERNMSG="Now you must compile the linux kernel...\nTo use a default config-file you must go in\nLoad An Alternate Configuration File and write ./config\nIf you want to edit the kernel by your hand you can do it without\nany problems. At the end, exit and save the config just created\n"
OKTOCON="Press Enter To Continue"
